export const JOKES = {
  RANDOM_REQUEST: 'JOKES RANDOM REQUEST',
  RANDOM_SUCCESS: 'JOKES RANDOM SUCCESS',
  RANDOM_FAILURE: 'JOKES RANDOM FAILURE',
};

export const NUMBER = {
  INCREMENT_CLASS_COMPONENT: 'NUMBER INCREMENT CLASS COMPONENT',
  INCREMENT_FUNCTIONAL_COMPONENT: 'NUMBER INCREMENT FUNCTIONAL COMPONENT',
};
